### ISSUE TITLE
Use of TimeSpan

### ISSUE THREAD

**Issue by Nekitaw** [markski1/WinTweakTool#1]
I have a little suggestion of use TimeSpan 

https://github.com/markski1/WinTweakTool/blob/master/WinTweakTool/ShutdownWindow.cs#L15

```c#
int hours = Convert.ToInt32(numericUpDown1.Value);
int minutes = Convert.ToInt32(numericUpDown2.Value);

// int total = (hours * 3600) + (minutes * 60);
// new TimeSpan(hours , minutes , seconds);
var shutdownTime = new TimeSpan(hours, minutes, 0);

// ...

// cmd.StartInfo.Arguments = $"-s -t {total}";
cmd.StartInfo.Arguments = $"-s -t {shutdownTime.TotalSeconds}";
```

I'm lazy to make a pull request, sorry 😓

**Comment by markski1** [comment]
Thanks for the suggestion. I do plan to use TimeSpan class in the future as the UI will offer an option to set a date and time of shutdown instead of just hours and minutes from now

**Comment by markski1** [comment]
Took a while, I was busy blah blah, but this was done for release 0.9 going up soon.

Commit: https://github.com/markski1/WinTweakTool/commit/de5762498335884f411606118ee98d6c36210c61

Thanks!
